import type { Metadata } from "next";
import { Manrope, Poppins } from "next/font/google";
import "./globals.css";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";

import { ReduxProvider } from "../lib/store/provider";
import ThemeProvider from "../lib/theme/ThemeProvider";
import ReactQueryProvider from "../lib/query/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Rentibles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider>
          <ReduxProvider>
            <ReactQueryProvider>
              <Toaster
                position="bottom-right"
                toastOptions={{
                  duration: 3000,
                }}
              />
              {children}
            </ReactQueryProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
